version: '2'
services:
  server:
    image: php:7.4-apache
    container_name: server
    volumes:
      - ./examples:/var/www/html
      - ./vendor:/var/www/vendor
  client:
    build: ./examples/client
    container_name: client
    volumes:
      - .:/tmp/ganesha
    working_dir: /tmp/ganesha
    environment:
      GANESHA_EXAMPLE_SERVER: "server"
      GANESHA_EXAMPLE_MEMCACHED: "memcached"
      GANESHA_EXAMPLE_REDIS: "redis"
      GANESHA_EXAMPLE_MONGO: "mongo"
      RUN_IN_DOCKER_COMPOSE: 1
  memcached:
    image: memcached:1.5.4
    container_name: memcached
  redis:
    image: redis:4.0.6
    container_name: redis
  mongo:
    image: mongo:4.0.6
    container_name: mongo
